### ISSUE TITLE
Replace the building Bash script with a Raft script 

### ISSUE THREAD

**Issue by nemoload** [protia/builder#1]

**Comment by iocoder** [comment]
The "build.sh" script here is just used for bootstrapping on UNIX. In order to build Protia, you have to build Systema first (which contains a component to process Raft recipe files). Once Systema is compiled and installed to "tools/" directory, the build.sh should use Systema to execute a RAFT file that builds the system.

If you are compiling the system from inside Protia itself, you don't need to execute build.sh, you can run the Raft script directly because Systema is a standard component of Protia.

So as you can see, build.sh is provided in order to automate the initial Systema build on UNIX. Hopefully would should make it easy for the users and for us too (while we are developing the system).

**Comment by nemoload** [comment]
Raft scripts should work fine on UNIX so I suppose we should unify our scripting language across the operating systems?

**Comment by iocoder** [comment]
As we explained before, we don't want to come up with a long list of pre-requisite packages to be installed on UNIX as a requirement for compiling the system.

Also, if we use any external program for developing the platform, we have to provide a *port* of the same program inside Protia. You shouldn't write "two" versions of your building scripts.
